import Head from 'next/head'
import Header from '../../components/organisms/header/Header'
import BasicsPricing from '../../components/organisms/pricing/BasicsPricing'

export default function Home() {
  return (
    <div>
      <Head>
        <title>LaBonneCote</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>

      <BasicsPricing/>
    </div>
  )
}
