import { CheckCircleIcon } from '@heroicons/react/outline'
import Head from 'next/head'
import BlueButton from '../../components/atoms/button/BlueButton'
import Header from '../../components/organisms/header/Header'
import PremiumPricing from '../../components/organisms/pricing/PremiumPricing'

export default function Home() {
  return (
    <div>
      <Head>
        <title>LaBonneCote</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>

      <PremiumPricing/>
    </div>
  )
}
